version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Debug
  - Release

platform:
  - x64
  - x86

build_script:
  - nuget restore
  - msbuild /t:Rebuild /p:Platform="%PLATFORM%" /p:Configuration="%CONFIGURATION%" WebViewBrowserApp.sln
  - 7z a -r %APPVEYOR_PROJECT_NAME%_%CONFIGURATION%_%PLATFORM%.7z %CONFIGURATION%_%PLATFORM%

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)_$(configuration)_$(platform).7z
