version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Debug
  - Release

platform:
  - x64
  - x86

build_script:
  - C:/msys64/usr/bin/wget.exe -nv "https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe"
  - nuget restore
  - msbuild /t:Rebuild /p:Platform="%PLATFORM%" /p:Configuration="%CONFIGURATION%" WebViewBrowserApp.sln
  - call rcupdate.bat "%CONFIGURATION%_%PLATFORM%\WebView2Browser.exe"
  - 7z a -r %APPVEYOR_PROJECT_NAME%_%CONFIGURATION%_%PLATFORM%.7z %CONFIGURATION%_%PLATFORM%

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)_$(configuration)_$(platform).7z
